export interface Customer {
  ID: string;
  Código: string;
  Nome: string;
  Fantasia: string;
  Endereço: string;
  Número: string;
  Complemento: string;
  Bairro: string;
  CEP: string;
  Cidade: string;
  UF: string;
  Contatos: string;
  Fone: string;
  Fax: string;
  Celular: string;
  'E-mail': string;
  'Web Site': string;
  'Tipo pessoa': string;
  'CNPJ / CPF': string;
  'IE / RG': string;
  'IE isento': string;
  Situação: string;
  Observações: string;
  'Estado civil': string;
  Profissão: string;
  Sexo: string;
  'Data nascimento': string;
  Naturalidade: string;
  'Nome pai': string;
  'CPF pai': string;
  'Nome mãe': string;
  'CPF mãe': string;
  Segmento: string;
  Vendedor: string;
  'Tipo contato': string;
  'E-mail para envio NFe': string;
  'Limite de crédito': string;
  'Cliente desde': string;
  'Próxima visita': string;
  'Condição de pagamento': string;
  'Regime tributário': string;
}
