import type { Metadata } from 'next';
import './globals.scss';
import 'dotenv/config';
import ClientProvider from './ClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <head>
        <script src='https://viewport-tester.com/delta/static/viewport-tester/js/utils/ChildFrame.js'></script>
        <link
          rel='stylesheet'
          href='https://viewport-tester.com/delta/static/viewport-tester/css/utils/childFrame.css'
        ></link>
      </head>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
